apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "evnConfigMapName" . | nindent 2}}
data:
  JDK_JAVA_OPTIONS: -Dspring.config.additional-location={{ .Values.configMap.mountPath }}/{{ .Values.configMap.filename }}