app:
  name: &appName muffin-wallet
  port: &appPort 8081
  image: aadan1lov/muffin-wallet:1.1.0
  imagePullPolicy: Always
  replicasCount: 3
  probes:
    liveness:
      httpGet:
        path: /actuator/health/liveness
        port: *appPort
      initialDelaySeconds: 90
      periodSeconds: 5

    readiness:
      httpGet:
        path: /actuator/health/readiness
        port: *appPort
      initialDelaySeconds: 90
      periodSeconds: 10

service:
  name: *appName
  type: ClusterIP
  port: &servicePort 80

db:
  url: jdbc:postgresql://host.minikube.internal:5432/muffin_wallet
  username: muffin-wallet

configMap:
  name: *appName
  mountPath: /app/config
  filename: application.yaml

secret:
  name: *appName

external:
  muffinCurrency:
    url : http://muffin-currency:8083/rate
